version: 2

sources:
  - name: snowplow
    description: pageview events from snowplow extension
    database: raw

    loaded_at_field: collector_tstamp
    freshness:
      warn_after: {count: 1, period: hour}
    tables:
      - name: events
        description: raw payment data
